In [1]:
# Uso do notebook para testar hipoteses antes de ir para o power bi
# Importando Pandas para obter base gold (tratada)
import pandas as pd

# Importando a base gold
df = pd.read_csv('../data/processed/base_historico.csv')

In [2]:
df.head()

,RA,Fase,Turma,Nome Anonimizado,Ano nasc,Idade,Gênero,Ano ingresso,Instituição de ensino,Pedra,...,Ing,IPV,IAN,Fase Ideal,Defasagem,Ano,Data de Nasc,IPP,Escola,Ativo/ Inativo
0,RA-1,7,A,Aluno-1,2003.0,19,Menina,2016,Escola Pública,Quartzo,...,6.0,7.278,5.0,Fase 8 (Universitários),-1,2022,NaN,NaN,NaN,NaN
1,RA-2,7,A,Aluno-2,2005.0,17,Menina,2017,Rede Decisão,Ametista,...,9.7,6.778,10.0,Fase 7 (3º EM),0,2022,NaN,NaN,NaN,NaN
2,RA-3,7,A,Aluno-3,2005.0,17,Menina,2016,Rede Decisão,Ágata,...,6.9,7.556,10.0,Fase 7 (3º EM),0,2022,NaN,NaN,NaN,NaN
3,RA-4,7,A,Aluno-4,2005.0,17,Menino,2017,Rede Decisão,Quartzo,...,8.7,5.278,10.0,Fase 7 (3º EM),0,2022,NaN,NaN,NaN,NaN
4,RA-5,7,A,Aluno-5,2005.0,17,Menina,2016,Rede Decisão,Ametista,...,5.7,7.389,10.0,Fase 7 (3º EM),0,2022,NaN,NaN,NaN,NaN

In [3]:
# Agrupando por ano para obter a média da nota IDA ao longo dos anos
df_media_ida_ano = df.groupby('Ano')['IDA'].mean().reset_index()
df_media_ida_ano.head()

    Ano       IDA
0  2022  6.092907
1  2023  6.663394
2  2024  6.351422

In [6]:
# Agrupando por ano e por fase para obter a média da nota IDA ao longo dos anos e fases
df_media_ida_ano_fase = df.groupby(['Ano', 'Fase'])['IDA'].mean().reset_index()
df_media_ida_ano_fase.head(60)

     Ano  Fase       IDA
0   2022     0  7.140000
1   2022     1  6.464062
2   2022     2  5.406452
3   2022     3  5.141892
4   2022     4  6.052632
5   2022     5  5.873333
6   2022     6  6.694444
7   2022     7  5.252381
8   2023     0  7.422078
9   2023     1  6.814451
10  2023     2  6.736683
11  2023     3  5.746970
12  2023     4  6.004255
13  2023     5  5.904615
14  2023     6  6.809091
15  2023     7  7.810000
16  2023     8       NaN
17  2024     0  7.320153
18  2024     1  6.790541
19  2024     2  6.250000
20  2024     3  5.347630
21  2024     4  5.878986
22  2024     5  6.453333
23  2024     6  7.230000
24  2024     7  5.810360
25  2024     8  8.000000
26  2024     9       NaN

In [5]:
# mostrar valores unicos da coluna fase
df['Fase'].unique()

array([7, 6, 5, 4, 3, 2, 1, 0, 8, 9])